### ISSUE TITLE
App crashes when posting notification on (some?) Android 6 devices - Lenovo PHAB2 Pro

### ISSUE THREAD

**Issue by simekadam** [covid19cz/erouska-android#142]
Our biggest crash at the moment. And specific to this one lenovo device. 🙂 
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at android.app.Notification$Builder.processLegacyText(Notification.java:3211)
       at android.app.Notification$Builder.access$1100(Notification.java:2009)
       at android.app.Notification$BigTextStyle.makeBigContentView(Notification.java:4139)
       at android.app.Notification$BigTextStyle.populateBigContentView(Notification.java:4177)
       at android.app.Notification$Style.buildStyled(Notification.java:3849)
       at android.app.Notification$Builder.build(Notification.java:3656)
       at androidx.core.app.NotificationCompatBuilder.buildInternal(NotificationCompatBuilder.java:355)
       at androidx.core.app.NotificationCompatBuilder.build(NotificationCompatBuilder.java:247)
       at androidx.core.app.NotificationCompat$Builder.build(NotificationCompat.java:1677)
       at cz.covid19cz.erouska.ui.notifications.CovidNotificationManager.postNotification(CovidNotificationManager.java:121)
       at cz.covid19cz.erouska.service.CovidService.createNotification(CovidService.java:229)
       at cz.covid19cz.erouska.service.CovidService.resume(CovidService.java:160)
       at cz.covid19cz.erouska.service.CovidService.start(CovidService.java:153)
       at cz.covid19cz.erouska.service.CovidService.onStartCommand(CovidService.java:127)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3011)
       at android.app.ActivityThread.access$2200(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5418)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by MCBlesk** [comment]
Jsem si docela jistý, že tohle už není aktuální.

**Comment by davidvavra** [comment]
This issue is not happening in v2 version of the app, closing.

**Comment by nehabalki** [comment]
@davidvavra How do you guys fix this issue? We do get same issue on Lenovo Android 6 devices.

**Comment by davidvavra** [comment]
We rewrote most part for the app for v2 and this issues stopped happening.
